### ISSUE TITLE
printStackTrace() in FontTable

### ISSUE THREAD

**Issue by fisch92** [radkovo/Pdf2Dom#22]
In class FontTable on line 200, there is a ex.printStackTrace();

It would be really nice to remove this and throw an Exception, so the user of your library can decied if he want to see the stacktrace or not.

**Comment by m-abboud** [comment]
My qualm with throwing an exception there is causing the whole PDF conversion to halt because of just one font that won't really ruin the final output without it is seems like a bad idea. And font library were using isn't the most stable.

Seems like it should just be doing the error log message there and the printStackTrace is extraneous and I forgot to remove it. Would just removing the printStackTrace work for you?

**Comment by fisch92** [comment]
Yes, this would work for me. Tank you!

**Comment by m-abboud** [comment]
Fixed this and other ones in above pull request
